name: Playwright Tests

on:
  # Run the workflow on push to main branch
  push:
    branches: [ main ]
  # Run the workflow on pull requests targeting main branch
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Set up Node.js environment
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    # Install project dependencies
    - name: Install dependencies
      run: npm ci

    # Install Playwright browsers
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Run Playwright tests
    - name: Run Playwright tests
      run: TEST_ENV=assessment npx playwright test

    # Upload Playwright test report as an artifact
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 10